# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-28 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0002_wish_date_granted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='date_granted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
